# Refer https://github.com/golangci/golangci-lint/blob/master/.golangci.yml for settings
run:
  skip-dirs:
    - vendor

linters:
  disable-all: true
  enable:
    - gofmt
    - deadcode
    - errcheck
    # gosimple disabled for this project only, getting below errors that does not have to be fixed
    # pkg/jsondatavalidator/jsondatavalidator.go:157:10: S1034: assigning the result of this type assertion to a variable (switch val := val.(type)) could eliminate type assertions in switch cases (gosimple)
    #                switch val.(type) {
    #- gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck