# Refer https://github.com/golangci/golangci-lint/blob/master/.golangci.yml for settings
run:
  skip-dirs:
    - vendor

linters:
  disable-all: true
  enable:
    - gofmt
    - deadcode
    - errcheck
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck